export const dummyProjects = [
  {
    title: "Merchant Analysis",
    requirements: ["flutter", "bloc", "provider"],
    description: "Merchant Handler with Ease",
    status: "In Progress",
    majors: ["cs", "is"],
    id: 1,
  },
  {
    title: "E-Commerce Platform",
    requirements: ["react", "tailwind", "supabase"],
    description: "A platform for online shopping.",
    status: "In Progress",
    majors: ["swe", "cs"],
    id: 2,
  },
  {
    title: "Social Media App",
    requirements: ["flutter", "firebase", "riverpod"],
    description: "An app to connect people.",
    status: "Completed",
    majors: ["cs", "it"],
    id: 3,
  },
  {
    title: "Task Management Tool",
    requirements: ["nextjs", "react", "graphql"],
    description: "A tool to manage tasks and projects.",
    status: "Open",
    majors: ["ise", "swe"],
    id: 4,
  },
  {
    title: "Blog Website",
    requirements: ["nextjs", "markdown", "tailwind"],
    description: "A website for writing and sharing blogs.",
    status: "In Progress",
    majors: ["swe", "cs"],
    id: 5,
  },
  {
    title: "Weather App",
    requirements: ["flutter", "api integration", "riverpod"],
    description: "An app that provides weather updates.",
    status: "Completed",
    majors: ["cs", "is"],
    id: 6,
  },
  {
    title: "To-Do List App",
    requirements: ["flutter", "local storage", "provider"],
    description:
      "An app to manage daily tasks with features like adding, editing, and deleting to-do items.",
    status: "In Progress",
    majors: ["cs", "swe"],
    id: 7,
  },
  {
    title: "E-Commerce App",
    requirements: ["flutter", "firebase", "payment integration"],
    description:
      "A shopping app with product listings, cart functionality, and secure payment options.",
    status: "Not Started",
    majors: ["swe", "it"],
    id: 8,
  },
  {
    title: "Fitness Tracker",
    requirements: ["flutter", "api integration", "google fit"],
    description:
      "An app to track daily fitness activities like steps, workouts, and calories burned.",
    status: "Completed",
    majors: ["cs", "is"],
    id: 9,
  },
];
