export const dummyProjects = [
  {
    title: "Merchant Analysis",
    requirements: ["flutter", "bloc", "provider"],
    description: "Merchant Handler with Ease",
    status: "In Progress",
    major: "cs",
    id: 1,
  },
  {
    title: "E-Commerce Platform",
    requirements: ["react", "tailwind", "supabase"],
    description: "A platform for online shopping.",
    status: "In Progress",
    major: "swe",
    id: 2,
  },
  {
    title: "Social Media App",
    requirements: ["flutter", "firebase", "riverpod"],
    description: "An app to connect people.",
    status: "Completed",
    major: "cs",
    id: 3,
  },
  {
    title: "Task Management Tool",
    requirements: ["nextjs", "react", "graphql"],
    description: "A tool to manage tasks and projects.",
    status: "Open",
    major: "ise",
    id: 4,
  },
  {
    title: "Blog Website",
    requirements: ["nextjs", "markdown", "tailwind"],
    description: "A website for writing and sharing blogs.",
    status: "In Progress",
    major: "swe",
    id: 5,
  },
  {
    title: "Weather App",
    requirements: ["flutter", "api integration", "riverpod"],
    description: "An app that provides weather updates.",
    status: "Completed",
    major: "cs",
    id: 6,
  },
];
