module.exports.titles = [
    "Online Marketplace", "Social Media App", "Task Manager", "E-learning Platform", "Weather App",
    "Restaurant Finder", "Expense Tracker", "Fitness Tracker", "Portfolio Website", "Chatbot for Customer Service",
    "Inventory Management", "Blog Platform", "News Aggregator", "Event Management", "Music Streaming App",
    "Video Sharing Platform", "Book Store", "Cooking Recipe App", "Personal Finance App", "Travel Booking System",
    "Educational Games", "Project Management Tool", "Digital Art Gallery", "Task Automation App", "Real Estate Portal",
    "Language Learning App", "Music Production Software", "Fitness Tracker", "Crypto Portfolio Tracker", "Online Auction System",
    "Video Conferencing App", "Dating App", "Job Portal", "Health Monitoring System", "Recipe Sharing Platform",
    "Virtual Shopping Assistant", "Crowdfunding Platform", "Code Sharing Platform", "Private Messaging App", "Local News App",
    "VR Travel Experience", "Customer Feedback System", "Real-Time Sports Scores", "Mobile Banking App", "Online Polling System",
    "Digital Portfolio", "Customizable Blog Platform", "Job Search Aggregator", "Customer Loyalty Program", "Online Quiz App",
    "Personalized Shopping App", "Task Scheduler", "Home Improvement Planner", "Online Ticket Booking", "Document Management System",
    "Subscription Management App", "Carpooling App", "Group Collaboration Tool", "Property Rental System", "Peer-to-Peer Lending App",
    "Recipe Generator", "Food Delivery App", "Pet Care App", "Online Learning Portal", "Invoice Generator",
    "Social Networking App", "Expense Splitter", "Music Library", "Learning Management System", "Online Polling App",
    "Event Ticketing Platform", "AI Chatbot", "Newsletters Platform", "Contact Management App", "Translation Tool",
    "Workout Planner", "Freelancer Marketplace", "Voice Assistant App", "Remote Desktop App", "Online Voting System",
    "Travel Planner", "Employee Engagement App", "Smart Home Control", "Movie Database", "Travel Guide App",
    "Freelancer Task Manager", "Food Tracking App", "Language Translator", "Task Management System", "Personal Assistant",
    "Educational App", "Content Management System", "Workforce Management Tool", "Online Classifieds", "Health & Wellness App",
    "Financial Dashboard", "Group Messaging App", "Cloud Storage", "Photo Editor", "Team Collaboration Tool"
];

module.exports.startDates = [
    "2024-09-15", "2024-10-01", "2024-08-25", "2024-07-10", "2024-09-05",
    "2024-09-20", "2024-08-15", "2024-06-30", "2024-10-10", "2024-08-05",
    "2024-07-01", "2024-08-10", "2024-09-25", "2024-07-14", "2024-09-03",
    "2024-08-07", "2024-10-05", "2024-08-18", "2024-09-11", "2024-06-22",
    "2024-09-12", "2024-08-21", "2024-09-09", "2024-07-18", "2024-09-17",
    "2024-08-29", "2024-06-17", "2024-09-02", "2024-07-30", "2024-09-10",
    "2024-08-13", "2024-07-23", "2024-09-27", "2024-06-12", "2024-07-05",
    "2024-09-19", "2024-10-02", "2024-06-27", "2024-08-01", "2024-09-06",
    "2024-07-08", "2024-09-23", "2024-08-24", "2024-06-19", "2024-09-14",
    "2024-08-28", "2024-09-08", "2024-07-15", "2024-09-30", "2024-08-17",
    "2024-06-25", "2024-09-13", "2024-07-20", "2024-09-22", "2024-08-26",
    "2024-06-15", "2024-09-04", "2024-07-03", "2024-09-18", "2024-08-22",
    "2024-06-29", "2024-09-24", "2024-07-11", "2024-09-28", "2024-08-30",
    "2024-06-20", "2024-09-16", "2024-07-06", "2024-09-21", "2024-08-27",
    "2024-06-26", "2024-09-01", "2024-07-26", "2024-09-07", "2024-08-14",
]
module.exports.descriptions = [
    "A web application for users to buy and sell products, with a secure payment system.",
    "A platform for users to share posts, photos, and interact with each other.",
    "A tool to help users manage tasks, set deadlines, and track progress.",
    "An online platform for students to access courses, assignments, and interact with instructors.",
    "A mobile app that provides real-time weather updates based on location.",
    "A web app that helps users discover nearby restaurants.",
    "A budgeting app that tracks daily expenses and helps save money.",
    "An app that tracks workouts and monitors progress.",
    "A personal website to showcase projects, skills, and accomplishments.",
    "An AI-powered chatbot integrated into websites to assist customers.",
    "A system to track inventory and manage stock levels.",
    "A platform for users to write and publish blogs.",
    "A website that collects news from various sources.",
    "A platform to plan and manage events, from invitations to follow-ups.",
    "A service that lets users stream music online.",
    "A platform for sharing and discovering videos.",
    "A website for buying and selling books.",
    "An app that helps users find and share recipes.",
    "An app that helps users manage their personal finances.",
    "A system to help users book and plan travel arrangements.",
    "A collection of educational games for learning purposes.",
    "A tool to manage projects, tasks, and teams.",
    "An online gallery for showcasing digital artwork.",
    "An app for automating repetitive tasks.",
    "A real estate website for buying, selling, and renting properties.",
    "An app to help users learn new languages through various exercises.",
    "Software for creating and producing music.",
    "A tool for tracking cryptocurrency portfolios.",
    "An online auction platform for various products.",
    "A video conferencing app for remote communication.",
    "A platform for users to meet new people and date.",
    "A job portal for job seekers and employers.",
    "A system for tracking and monitoring health-related metrics.",
    "An app for sharing and discovering recipes.",
    "A virtual shopping assistant for e-commerce sites.",
    "A crowdfunding platform for raising funds for projects.",
    "A platform for sharing and collaborating on code.",
    "An app for secure, private messaging between users.",
    "A local news app to stay updated with community news.",
    "A virtual reality app to explore different travel destinations.",
    "A system to gather and analyze customer feedback.",
    "A platform for live sports scores and updates.",
    "A mobile banking application to manage accounts and transactions.",
    "A polling system for online surveys and votes.",
    "A platform to showcase your digital portfolio.",
    "A customizable blog platform with user-friendly features.",
    "An aggregator for job postings from various sources.",
    "A loyalty program to reward customers for their purchases.",
    "A quiz app with various categories of questions.",
    "An app that provides personalized shopping recommendations.",
    "A tool for scheduling and managing daily tasks.",
    "A platform for planning and organizing home improvement projects.",
    "A ticket booking system for events, concerts, and travel.",
    "A document management system for storing and organizing files.",
    "An app for managing subscriptions to different services.",
    "A carpooling app that connects drivers and passengers.",
    "A collaborative platform for teams to work together.",
    "A rental system for booking properties for short-term stays.",
    "A peer-to-peer lending platform for financial transactions.",
    "An app that generates personalized recipes.",
    "A food delivery service that connects customers and restaurants.",
    "An app for tracking pets' health and activities.",
    "A platform for online learning, courses, and quizzes.",
    "A tool for generating invoices for businesses.",
    "A social networking platform for staying connected with friends.",
    "An expense splitter for managing group expenses.",
    "A music library for organizing and playing music files.",
    "A system for managing and tracking courses and learning materials.",
    "A platform for conducting online polls and surveys.",
    "A ticketing platform for selling and managing event tickets.",
    "An AI chatbot for customer service and support.",
    "A system for sending and managing newsletters.",
    "An app to manage contacts and stay connected with people.",
    "A translation tool for converting text into different languages.",
    "A workout planner for organizing and tracking fitness routines.",
    "A marketplace for freelancers to find tasks and clients.",
    "A voice assistant app to perform tasks hands-free.",
    "An app for remote desktop access and management.",
    "A system for online voting and elections.",
    "A tool to help users plan trips and book travel.",
    "An app to engage employees in company activities.",
    "A smart home control app for managing devices.",
    "A movie database for finding information about films.",
    "A travel guide app that helps users plan their trips.",
    "A task manager for freelancers to organize their work.",
    "An app for tracking food consumption and calories.",
    "A language translation app for traveling.",
    "A task management system for teams and businesses.",
    "An AI-powered personal assistant for organizing tasks.",
    "A collection of educational apps for children.",
    "A content management system for publishing websites.",
    "A workforce management tool for businesses.",
    "A platform for buying and selling products locally.",
    "An app for tracking health and wellness progress.",
    "A dashboard for monitoring financial data and performance.",
    "A messaging app for group communication.",
    "A cloud storage service for saving and sharing files.",
    "An app for editing and enhancing photos.",
    "A collaboration tool for teams to share documents."
];