const majors = [
  { name: "ACC", id: 1 },
  { name: "ASFM", id: 2 },
  { name: "AE", id: 3 },
  { name: "ARCH", id: 4 },
  { name: "BIOE", id: 5 },
  { name: "CHE", id: 6 },
  { name: "CIV", id: 7 },
  { name: "CEN", id: 8 },
  { name: "CS", id: 9 },
  { name: "CIE", id: 10 },
  { name: "EE", id: 11 },
  { name: "ESE", id: 12 },
  { name: "FIN", id: 13 },
  { name: "GEO", id: 14 },
  { name: "GPH", id: 15 },
  { name: "HRM", id: 16 },
  { name: "ISE", id: 17 },
  { name: "ID", id: 18 },
  { name: "MGT", id: 19 },
  { name: "MIS", id: 20 },
  { name: "MKT", id: 21 },
  { name: "MSE", id: 22 },
  { name: "MATH", id: 23 },
  { name: "ME", id: 24 },
  { name: "MIN", id: 25 },
  { name: "PE", id: 26 },
  { name: "PHYS", id: 27 },
  { name: "SSC", id: 28 },
  { name: "SWE", id: 29 },
];

export default majors;
